### ISSUE TITLE
Successful orders still show an amount due and don't generate invoices.

### ISSUE THREAD

**Issue by blueninja2** [oxipay/oxipay-magento-1.x#30]
Oxipay orders are now being marked as **Complete**. However:

1 - An invoice is not being generated once the order is successfully processed by Oxipay.
2 - Total Due on the order information page is not set to "0.00 - if the order is for **$428.12**, it still shows **428.12** is due.

See screenshot below for an example that was provided to us by a merchant.

![image](https://cloud.githubusercontent.com/assets/22509613/24275357/bec21f88-107e-11e7-9f40-47e7eb6f95da.png)

**Comment by esteban-terem** [comment]
Commit a7987d0344d4cc3ffae96cab6d33faeeb73c45f2 adds functionality to:

* Set the total paid on the order
* Send new order email to customer

![image](https://cloud.githubusercontent.com/assets/26374597/24281546/92002b8c-10ad-11e7-9fce-88a8760719ef.png)

Please confirm this email corresponds to the invoice the client is referring to:

![image](https://cloud.githubusercontent.com/assets/26374597/24281567/c57f97cc-10ad-11e7-9dbd-9fb256b6687a.png)

**Comment by blueninja2** [comment]
Hi Esteban,

I tested the fix – the Total Due is now being set correctly to $0.00 as it should.

However, there is still the issue with invoices.  If a customer places an order and then navigates to Sales  invoices then they still don’t see an invoice for that order.

I have also spoken with the merchant and they said that in terms of email functionality or receipts; there’s no issues with that.

Let me know if you’d like more information from the merchant on this issue.

Thanks,
Sam

![image](https://cloud.githubusercontent.com/assets/22509613/24342150/852af0da-1306-11e7-823b-31eade835c5c.png)

**Comment by jmcmanamey-terem** [comment]
This ticket is currently on hold as per discussion with Anthony Thrassis. Terem will propose a new order status flow in line with the recommended Magento order flow.

**Comment by hellotaotao** [comment]
Tested against Magento 1.4 and Magento 1.9 and PASSED
