### ISSUE TITLE
Detect store statuses and also replace processing with pending

### ISSUE THREAD

**Issue by blueninja2** [oxipay/oxipay-magento-1.x#32]
Hi,

One of our merchants have come back to us saying that the plugin is using hard-coded statuses as opposed to using statuses that the store has setup.

Can you please advise if it is possible to use store configured statuses and if these are not configured then we fall back to hard-coded statuses.

Also, we would like to replace the processing status with the pending status. One of our merchants thought that the processing status meant that the payment had already been made and thought that pending was more appropriate.

Let me know if you would like further information.

**Comment by jmcmanamey-terem** [comment]
This issue will be looked at as part of a redesign of the Magento order status flow. One of the things we will look at is the ability for the merchant to have some control over the status being set for orders that are waiting on Oxipay to complete and orders that have been confirmed by Oxipay

**Comment by esteban-terem** [comment]
Plase see #34 for the new order state flow.
