### ISSUE TITLE
Special characters in last name result in 401 Error

### ISSUE THREAD

**Issue by blueninja2** [oxipay/oxipay-magento-1.x#33]
A customer recently experienced a 401 error.
Examining the logs revealed that the last name that we registered for them was just the letter O.

The customer's last name had a special character such as an apostrophe - ' - and that the plug-in trimmed it and all the subsequent letters in the surname when calculating the signature and also when passing the transaction payload to Oxipay.

Please also apply the fix to other applicable fields that might have special characters such as suburb names for instance.

Testing Instructions
1 - Ensure a special character in surname doesn't result in 401 error.
2 - Ensure that the logs register the special character and customer's full last name.

**Comment by hellotaotao** [comment]
Tested against Magento 1.4 and Magento 1.9 and passed.
