### ISSUE TITLE
Update order state flow

### ISSUE THREAD

**Issue by jamesfmac** [oxipay/oxipay-magento-1.x#34]
As a merchant I need to be able to create invoices and ship product from Magento in order to complete my order lifecycle. 

States being used for orders in Magento will be updated to follow the Magento best practice for payment gateways. 

New States: 
- Payment Pending = Customer sent to Oxipay portal to complete payment
- Processing = Order approved by Oxipay, merchant should continue with invoicing and shipping
 
AC: 

- Orders are created in the correct states 
- Comments history accurately reflects state changes 
- Merchants are able to manually create invoices + ship orders approved by Oxipay

**Comment by blueninja2** [comment]
Tested and passed.
