### ISSUE TITLE
Allow merchants to select status for orders approved by Oxipay

### ISSUE THREAD

**Issue by jamesfmac** [oxipay/oxipay-magento-1.x#35]
As a merchant I want to be able to select the status that orders approved by Oxipay are set to in order to have control over my order workflow. 

AC: 

- Merchants can see a new field in the admin screen to set 'Status for approved orders' 
- Merchants are able to select any status mapped to state 'Processing' 
- Orders approved by Oxipay are set to the status configured by the merchant.

**Comment by hellotaotao** [comment]
This does not work in Magento 1.4 as 1.4 does not allow it

**Comment by hellotaotao** [comment]
Tested against Magento 1.9 and PASSED.
Not applicable to Magento 1.4
