### ISSUE TITLE
Insert default Oxipay status during plugin installation

### ISSUE THREAD

**Issue by jamesfmac** [oxipay/oxipay-magento-1.x#36]
As a merchant, I want to have the option of identifying orders processed by Oxipay so that I can remember to update the shipped status in the Oxiapy portal. 

AC

- Installing the Oxipay plugin creates a new status for state 'Processing' [status code 'oxipay_processed', label 'Oxipay Processed']
- New status is used as the default status for orders approved by Oxipay

**Comment by hellotaotao** [comment]
Tested against Magento 1.9 and PASSED.
Not applicable to Magento 1.4.

Note: Need to flush cache for the new status to show up. 
How to flush cache:
Admin Panel -> System -> Cache Management -> click the "Flush Magento Cache" button.
