### ISSUE TITLE
Allow merchants to automatically invoice orders

### ISSUE THREAD

**Issue by esteban-terem** [oxipay/oxipay-magento-1.x#37]
As a merchant, I want to have the option to choose if the orders approved by Oxipay are to be automatically invoiced, so that I don't need to invoice them manually.

AC:

* Merchants can see a new field in the admin screen to toggle the 'Automatic Invoice' functionality
* Orders approved by Oxipay are invoiced or not according to the option configured by the merchant.

**Comment by hellotaotao** [comment]
Tested against Magento 1.4 and Magento 1.9 and PASSED
