### ISSUE TITLE
Allow merchants to enable/disable email notifications on new orders 

### ISSUE THREAD

**Issue by esteban-terem** [oxipay/oxipay-magento-1.x#38]
As a merchant, I want to have the option to enable or disable the email notifications on new orders, to have control over the notifications sent to the customer.

AC:

* Merchants can see a new field in the admin screen to toggle the 'Email Customer' functionality
* Email notifications on new Orders approved by Oxipay are sent or not according to the option configured by the merchant.

**Comment by hellotaotao** [comment]
Tested against Magento 1.4 and Magento 1.9 and PASSED
