### ISSUE TITLE
"Total Paid" is double actual price when automatic invoicing is enabled.

### ISSUE THREAD

**Issue by blueninja2** [oxipay/oxipay-magento-1.x#40]
We have stumbled on adefect when invoicing is enabled – if enabled, the Total Paid for an order is double the actual price for the item – see screenshot below.
 
Also, the Quantity column will show 1 ordered item and 1 invoiced item – implying that 2 items were checked out – which might explain why the total paid is twice what it should be.

![image](https://cloud.githubusercontent.com/assets/22509613/24744379/02e438dc-1af1-11e7-92da-d1d23c703423.png)

**Comment by hellotaotao** [comment]
Tested against Magento 1.4 and Magento 1.9 and PASSED
