### ISSUE TITLE
"Oxipay Processed"/"Processing" assigned at multiple stages of checkout process.

### ISSUE THREAD

**Issue by blueninja2** [oxipay/oxipay-magento-1.x#41]
In the Comments History section, the plugin is assigning “Oxipay Processed” to orders at multiple times and sometimes at in-correct stages of the checkout process.

As per screenshot below, Oxipay Processed is assigned when (1) being directed to Oxipay, (2) when approved by Oxipay and when (3) going back to the cart. Can you please advise on this. I believe it should only appear once – maybe when the success page is displayed on Oxipay (point 2).

Also, each of the Oxipay Processed status has a Customer Notified subheading; does that imply that an email receipt will be sent out to the customer when an order is “Oxipay Processed” .

![image](https://cloud.githubusercontent.com/assets/22509613/24744394/16595c3a-1af1-11e7-87dd-3261e672ea6f.png)

**Comment by esteban-terem** [comment]
This was still happening for "Declined" orders.

**Comment by blueninja2** [comment]
This is tested and passed

**Comment by hellotaotao** [comment]
Tested against 1.4 and 1.9 and PASSED
