### ISSUE TITLE
Oxipay orders re-direct back to error page on Magento 1.9 and 1.4

### ISSUE THREAD

**Issue by blueninja2** [oxipay/oxipay-magento-1.x#45]
Customers that successfully process an order on Oxipay are re-directed back to an error page on Magento.

![image](https://cloud.githubusercontent.com/assets/22509613/24850042/ab850f1a-1e0d-11e7-8441-0499fd2fbd2c.png)

![image](https://cloud.githubusercontent.com/assets/22509613/24850046/affb3272-1e0d-11e7-955e-08b79c64f8f3.png)

**Comment by hellotaotao** [comment]
Tested against Magento 1.4 and Magento 1.9 and PASSED
