### ISSUE TITLE
"Oxipay Processed" not getting displayed in Magento 1.4

### ISSUE THREAD

**Issue by hellotaotao** [oxipay/oxipay-magento-1.x#49]
When testing in Magento 1.4, we cannot see the **Oxipay Processed** option from the drop-down. We can only see **Processing**.

![image](https://cloud.githubusercontent.com/assets/1796860/24986350/dcba732c-2038-11e7-9a60-1f96fb83c412.png)

**Comment by blueninja2** [comment]
The updated custom flow that Terem have worked on is not supported in Magento 1.4; only in 1.9. Closing off this ticket.
