### ISSUE TITLE
Canceled Oxipay transaction does not created a correct comment

### ISSUE THREAD

**Issue by hellotaotao** [oxipay/oxipay-magento-1.x#53]
Cancelled Oxipay transaction does not create a correct comment in the comment's history section.
In comments history, comment for cancelled order is missing the Magento order id

Please see screenshot below.

![image](https://cloud.githubusercontent.com/assets/1796860/25167244/de9b044c-251d-11e7-82a5-9dd9bda93ea4.png)

**Comment by blueninja2** [comment]
Tested in Magento 1.4 and 1.9 and passed.
