### ISSUE TITLE
Magento 1.4 doesn't send email receipts if the user closes the browser on the success screen

### ISSUE THREAD

**Issue by sam-oxipay** [oxipay/oxipay-magento-1.x#63]
On Magento 1.4, if a user processes an Oxipay transaction and are then presented with the success page - if they close the browser on the success page then they will only get an email from Oxipay and not from Magento.

They will only get an email receipt from Magento if they wait until they are re-directed back to the shopping cart.

Can you please resolve this so that even if a user closes the browser on the success screen, they still get an email receipt from Magento 1.4

**Comment by jmcmanamey-terem** [comment]
@blueninja2 what state is the order in Magento after this occurs? Which environment where you using to produce this bug i.e. local VM or AWS.

**Comment by blueninja2** [comment]
@jmcmanamey-terem no probs, will update the ticket with the additional details.

**Comment by blueninja2** [comment]
This is due to the async callback - link to the other ticket.
