### ISSUE TITLE
[QAIT]  Oxipay Checkout modal window fields not populating as per shared document. 

### ISSUE THREAD

**Issue by ramanjeetaulakh-qait** [oxipay/oxipay-magento-1.x#64]
Steps to Replicate:
1) Copying the oxipay-magento-1.x zipped files into the app folder under the Magento root directory.
2) Login into Admin Panel.
3) Navigate to System> Cache Management
4) Click on the Flush Magento Cache button.
5) Navigate to System> Configuration> Payment Methods
6) Verify that Oxipay Checkout modal window appears.
7) Check for fields under Oxipay Checkout modal window

Result:
No of Fields appearing on Oxipay Checkout modal window are different from that of the one shared in document. 
Fields Appearing as :
- Enabled
- Merchant Number
- API Key	
- Oxipay Gateway URL
- Status for Oxipay Approved Orders
- Automatic Invoice		
- Email Customer

Fields on document are
- Enabled
- Merchant Number
- API Key	
- Test Mode
- Gateway Base URL
- Gateway URL
- New Order Status

Expected:
Files should appear as per documention or the document should be updated accordingly. 

Screen Cast: http://screencast-o-matic.com/watch/cbfrXxXQLJ
Shared Document: http://docs.oxipay.com.au/platforms/magento_1/

Test Case:  
#5 - "Verify that system displays following options under Oxipay Plugin Settings:
 -  Enabled: Dropdown. When yes, it enables the payment method on the merchant store otherwise, disabled
 - Merchant Number: Textbox. Uniquely identifies the merchant
 - API Key: Textbox. Unique key to verify whether the payment request is from valid merchant
 - Test Mode: Dropdown. When yes, Oxipay runs on test environment and no real payments are made
 - Gateway Base URL: Textbox. This is the URL through which site communicates with Oxipay payment   gateway 
 - Gateway URL: Textbox
 - New order status: Dropdown"

Environment stack/versions
 - Ubuntu: 16.04 LTS 
 - PHP version: PHP 5.6.30
 - mysql Ver: 14.14
 - Apache: 2.4.18
 - Magento ver: 1.9.1.0

**Comment by blueninja2** [comment]
Hi Raman, we have now updated the documentation so that the screenshot reflects the new user interface of the plugin's setting area.
Please review the updated documentation at : http://docs.oxipay.com.au/platforms/magento_1/ and let us know if it looks okay or if there are other issues.
Thanks,

**Comment by ramanjeetaulakh-qait** [comment]
Verified and found that Document is updated now and Number of Fields appearing on Oxipay Checkout modal window is coming as per updated document.

Marking this as closed. 

Thanks!
