### ISSUE TITLE
[QAIT] Magento/WooCommerce>Cancel Button (Details Page) : System logs out user from Oxipay and navigate to login page instead of navigating to cart.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-magento-1.x#67]
Steps to Replicate:

Launch URL: http://115.113.54.81/mage1/
Add any item to cart any then click on ‘Proceed to checkout’ button
Login using valid credentials
Fill all the necessary details and select Oxipay in payment information
Click on ‘Place Order’ button
Login to Oxipay payment gateway using valid credentials
Click on ‘Cancel’ button present on  'Enter your details page'
Verify the result

Acceptance Criteria: System should navigate user to cancelled page indicating the user that purchase is cancelled.

Screen Cast: https://www.screencast.com/t/u1DIbXPBNVY
Shared Document: http://docs.oxipay.com.au/platforms/magento_1/

Test Case :
#43 - Verify that when payment is cancelled in Oxipay, application navigates to cancelled page indicating the user that purchase is cancelled

Tech Stack Details.

Ubuntu: 16.04 LTS
PHP version: PHP 5.6.30
mysql Ver: 14.14
Apache: 2.4.18
Magento ver: 1.9.1.0

**Comment by blueninja2** [comment]
Investigate internally - possibly an issue with the Oxipay application.

**Comment by hellotaotao** [comment]
The procedures demonstrated in the screen cast does not reflect the test case. It is desired behaviour that cancelling from registration page takes you back to login page. In the case of the screen cast, it was cancelling the registration rather than cancelling the payment.

Also, this has nothing to do with the plugin.
