### ISSUE TITLE
[QAIT] Magento > Suggested Enhancements 

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-magento-1.x#69]
1. Oxipay payment page> 'Save card details' option should be there.
2. Enhancement - Order email - Email should display the product details for reference.
3. Enhancement - Order Email - Link to track the order is not given in the email as it is mentioned on the Order Confirmation Page.
4. Enhancement > Order # should be displayed in the email subject line for better usability

**Comment by Piyush-Qait** [comment]
More Enhancements in Magento-Oxipay

1. Enhancement - Order email - Email should display the product details for reference.
2. Enhancement - Order Email - Link to track the order is not given in the email as it is mentioned on the Order Confirmation Page.
3. Enhancement > Order # should be displayed in the email subject line for better usability

**Comment by blueninja2** [comment]
To be assigned to Matt to investigate internally.
