### ISSUE TITLE
[QAIT] Magento/WooCommerce> 'Recent Purchases' & 'All Purchase' details are not displayed on customer's oxipay dashboard.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-magento-1.x#71]
Steps to Reproduce:

1) Launch the Magento URL:http://115.113.54.81/mage1/
2) Login with valid credentials says 'testuser@test.com/123456'.
3) Add a product to cart & checkout using OXIPAY.
4) Verify user get Purchase Approved email with button 'Login to Oxiplay'.
5) Click on button 'Login to Oxiplay'.
6) Verify user is get navigated to oxipay customer dashboard login page.
7) Login using valid credentials.
8) Verify

Actual Result: 'Recent Purchases' & 'All Purchase details' are not displaying on customer's oxipay dashboard while invoice is getting generated on Magento. 
Acceptance Criteria: 'Recent Purchases' & 'All Purchase' details should be displayed on customer's Oxipay dashboard.

Screen Cast: https://www.screencast.com/t/wuaySclh9T
Shared Document: http://docs.oxipay.com.au/platforms/magento_1/

NOTE: Reproducible on Magento ver: 1.9.1.0 and Magento 1.4.2.0

Tech Stack:
Ubuntu (16.04 LTS)
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)
Magento 1.9.1.0
Oxipay_Magento 1.x_v0.3.21

Ubuntu 14.04
PHP version: (5.5.9)
Apache: (2.4.7)
mysql: (14.14)
Magento 1.4.2.0
Oxipay_Magento1.x_v0.3.21

**Comment by am-oxipay** [comment]
resolved
