### ISSUE TITLE
[QAIT] Declined transaction> Click on 'Return to Cart' button> Application displays message 'AN ERROR OCCURRED IN THE PROCESS OF PAYMENT' on Magento store

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-magento-1.x#74]
Steps to Replicate:

1. Launch URL: http://115.113.54.81/mage1/
2. Add multiple items to cart (cost more than A$625) any then click on ‘Proceed to checkout’ button
3. Login using valid credentials say: test_03@qait.com/qainfotech
4. Fill all the necessary details and select Oxipay in payment information
5. Click on ‘Place Order’ button
6. Login to Oxipay payment gateway using valid credentials say: piyush.srivastava@qainfotech.com /Password1
7. Verify that application navigates user to ‘Declined payment’ page
8. Click on 'Return to Cart' button and verify the result on Magento Store

Acceptance Criteria: Application should not display any error message "'AN ERROR OCCURRED IN THE PROCESS OF PAYMENT'" and directs user to Shopping Cart page with all previously items added to cart

Screen Cast: https://www.screencast.com/t/CMXzED25P4
Shared Document: http://docs.oxipay.com.au/platforms/magento_1/

Test Case :
#41 - "Verify that when payment is declined in Oxipay, previously active cart remains enable”

**NOTE:** Reproducible on both Magento v1.9.1.0 and v1.4.2.0

**Tech Stack Details:**
Ubuntu (16.04 LTS) 
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)
Magento 1.9.1.0
Oxipay_Magento 1.x_v0.3.21

Ubuntu 14.04
PHP version: (5.5.9)
Apache: (2.4.7)
mysql: (14.14)
Magento 1.4.2.0
Oxipay_Magento1.x_v0.3.21

**Comment by hellotaotao** [comment]
The only issue here is the error message is not clear enough as it did not indicate the payment was "declined" and the reason of decline

**Comment by blueninja2** [comment]
To investigate what the standard procedure in Magento 1 to handling this sort of behaviour.
