### ISSUE TITLE
[QAIT] Oxipay payment gateway> Application does not redirect back to Oxipay cancelled page and does not display any message to end user when user cancels the payment

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-magento-1.x#76]
Steps to Replicate:

1. Launch URL: http://115.113.54.81/mage1/
2. Add any item to cart and then click on ‘Proceed to checkout’ button
3. Login using valid credentials say: test_03@qait.com/qainfotech
4. Fill all the necessary details and select Oxipay in payment information
5. Click on ‘Place Order’ button
6. Login to Oxipay payment gateway using valid credentials say: piyush.srivastava@qainfotech.com /Password1
7. Click on ‘Cancel’ button

Acceptance Criteria: Application should display some message like “Your order has been canceled”/

Shared Document: http://docs.oxipay.com.au/platforms/magento_1/

Test Case:
#43, #46- Verify that when payment is canceled in Oxipay, application navigates to canceled page indicating the user that purchase is canceled

NOTE: Reproducible on Magento ver: 1.9.1.0 and Magento 1.4.2.0

Tech Stack:
Ubuntu (16.04 LTS)
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)
Magento 1.9.1.0
Oxipay_Magento 1.x_v0.3.21

Ubuntu 14.04
PHP version: (5.5.9)
Apache: (2.4.7)
mysql: (14.14)
Magento 1.4.2.0
Oxipay_Magento1.x_v0.3.21

**Comment by hellotaotao** [comment]
Reproduced.
cancel after log-in to oxipay, you are taken back to shopping cart, with products still in there. 

This is behaviour is different from if you cancel in oxipay login page, which takes you to a page saying your purchase is cancelled.
