### ISSUE TITLE
[QAIT] Magento/WooCommerce>Oxipay Payment Gateway> Application logout the user from Oxipay when session timeouts (session gets over after 25-30 mins) and after login with same user, transaction gets approved 

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-magento-1.x#77]
Observation: When application logouts the user from Oxipay, it displays junk value like 4010000001 in the 'Email' field

Steps to Replicate:
1. Launch URL: http://115.113.54.81/mage1/
2. Add any item to cart any then click on ‘Proceed to checkout’ button
3. Login using valid credentials say: test06@qait.com/qainfotech
4. Fill all the necessary details and select Oxipay in payment information
5. Click on ‘Place Order’ button
6. Verify that user has been navigated to Oxipay payment gateway page
7. Login into Oxipay with valid credentials say: piyush.srivastava@qainfotech.com/Password1
8. Wait for 25-30 mins so that session gets destroyed
9. After 25-30 mins, enter the card details and click on ‘Confirm’ button
10. Verify that application logout the user from Oxipay after session timeout and after login with same credentials, transaction gets approved 

Acceptance Criteria:
Application should logout the user after session timeout and when user again login into Oxipay, it should display card details page

Screencast: https://www.screencast.com/t/lqgzCwYgR3

Test Case: #54 “Verify that during a transaction when max timeout is achieved user should not be able to complete the transaction.”

Shared Document: http://docs.oxipay.com.au/platforms/magento_1/

**NOTE:** Reproducible on both Magento v1.9.1.0 and v1.4.2.0

**Tech Stack Details:**
Ubuntu (16.04 LTS) 
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)
Magento 1.9.1.0
Oxipay_Magento 1.x_v0.3.21

Ubuntu 14.04
PHP version: (5.5.9)
Apache: (2.4.7)
mysql: (14.14)
Magento 1.4.2.0
Oxipay_Magento1.x_v0.3.21

**Comment by hellotaotao** [comment]
In my opinion:
1. this is not caused by the plugin.
2. this is not critical as it does not lead to any loss or damage anyway.

**Comment by blueninja2** [comment]
Issue with Oxipay - Matt to bring across to the JIRA board; not plugin specific.
