### ISSUE TITLE
[QAIT][Magento] : Oxipay Payment Gateway> User is able to make payment even if Merchant ID and API key are changed to some incorrect values from configuration settings.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-magento-1.x#80]
**Prerequisite:** User has changed API key and Merchant ID to any random value from admin configuration.

**Steps to reproduce:** 
Launch URL: http://115.113.54.81/mage1
Add any item in the cart and click on proceed.
On payment page select Oxipay.
Login using credentials:piyush.srivastava@qainfotech.com /Password1
Verify the result

**Observation:** _For WooCommerce and Prestashop application displays an error message that “You are not authorized to make this request” when the user clicks on Place Order after selecting Oxipay._

**Acceptance Criteria:** Application should display an error message and user should not be able to login into Oxipay if Merchant ID and API keys are changed.

**Screen Cast:** https://www.screencast.com/t/DNU9h0OXQhO 

**Shared Document:** http://docs.oxipay.com.au/platforms/magento_1/ 

**Test Case:**
#90: Verify that application displays an appropriate error message if any random value of API key and Merchant ID is saved in configuration and then user tries to login into Oxipay payment gateway.

**Tech Stack:**
Ubuntu (16.04 LTS)
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)
Magento 1.9.1.0
Oxipay_Magento 1.x_v0.3.21

Ubuntu 14.04
PHP version: (5.5.9)
Apache: (2.4.7)
mysql: (14.14)
Magento 1.4.2.0
Oxipay_Magento1.x_v0.3.21

**Comment by hellotaotao** [comment]
I cannot replicate this error in our instance of Magento 1.9.2.4.

**Comment by blueninja2** [comment]
Move the ticket to the IR team; Irish to do more testing around this and determine impact analysis.

**Comment by am-oxipay** [comment]
unable to replicate
