### ISSUE TITLE
Missed file Model/Observer.php

### ISSUE THREAD

**Issue by haiacom** [oxipay/oxipay-magento-1.x#95]
in config.xml file, the module is defined a crontab 
<crontab>
        <jobs>
            <Oxipay_cancelOxipayPendingOrders>
                <schedule>
                    <cron_expr>*/2 * * * *</cron_expr>
                </schedule>
                <run>
                    <model>oxipayments/observer::cancelOxipayPendingOrders</model>
                </run>
            </Oxipay_cancelOxipayPendingOrders>
        </jobs>
    </crontab>
But there is no file named Observer.php in Mode/Observer.php

**Comment by am-oxipay** [comment]
This has been addressed
